// Import dependencies
import { Metadata } from 'next';
import { Inter } from 'next/font/google';

// Define the Inter font
const inter = Inter({ subsets: ['latin'] });

// Define metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

// Define the RootLayout component
export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
